name: Terraform

on:
  push:
    branches:
      - main
      - master
      - feature/terraform

  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Show Current Directory
        run: |
          pwd
          echo "Files in repository:"
          ls -la

      - name: Find Terraform Files
        run: |
          echo "Terraform files found:"
          find . -type f -name "*.tf"

      - name: Terraform Version
        run: terraform version

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan