name: Terraform

on:
  push:
    branches:
      - main
      - master
      - feature/terraform

  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Terraform-Landing-Zone

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform version

      - name: List Terraform Files
        run: |
          pwd
          ls -la
          find . -type f -name "*.tf"

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan